### ISSUE TITLE
Multiple reports: Can't register new account or send Tezos

### ISSUE THREAD

**Issue by jph108** [tezbox/web-wallet#12]
I have successfully activated my Crowdfunder account via activatez with my activation code, and can restore that wallet with the seed words, etc. in tezbox, both on the web and using the Chrome extension. I can see on tzscan.io that the activation status says Success, and both tezbox and tzscan.io say I have a balance in the account. However, when I click Add Account, it tells me "There was an error adding account. Please ensure your main account has funds available." in both the web wallet and Chrome extension. Not sure if I am doing something wrong or if it is a bug.

**Comment by jph108** [comment]
Just an update, this issue has now been reported by others on reddit in /r/tezos . It also is occurs in the Chrome plugin.

**Comment by jph108** [comment]
Adding a new account now results in the error: Operation Failed: Error (unregistered_delegate)

**Comment by RED29** [comment]
Same here, Operation Failed: Error (unregistered_delegate)

**Comment by stephenandrews** [comment]
Both error should be fixed in the latest updates

**Comment by JVsGithub** [comment]
Just downloaded desktop tezbox wallet.  I have tez in the wallet but it won't allow me to add an account.  Says there's no funds available.  Please advise?
