### ISSUE TITLE
TezBox Web Wallet does not detect my Nano Ledger S

### ISSUE THREAD

**Issue by awasunyin** [tezbox/web-wallet#33]
I have tried today to link my Nano Ledger S to TezBox, using the Web Wallet version on MacOS (tried Safari and Chrome).

My Ledger has Tezos Wallet installed and I left it connected with the app open. Then when clicking on "Link TezBox" it prompts: "please verify your address on your Nano Ledger S".

However, my ledger does not prompt anything. Maybe there are some issues related to detecting my Ledger?

The issue doesn't seem to appear with the native Desktop app, though.

**Comment by stephenandrews** [comment]
Some users reported re-installing the Tezos Wallet app and/or restarting your PC/Chrome seems to solve this bug. It seems to be a browser-based transport issue, that occurs at the LedgerJS level so there's not too much we can do if that's the case. If you continue to have issues, let me know, and we will keep trying to debug it.
