### ISSUE TITLE
Operation Failed! Please check your inputs

### ISSUE THREAD

**Issue by clu8** [tezbox/web-wallet#35]
I'm getting the error message `Operation Failed! Please check your inputs` when I try to send the maximum possible amount from my crowdsale address to another address, after a previous successful transfer to the same address. 

The same issue occurs with the web wallet and Windows desktop wallet. Any ideas?

**Comment by stephenandrews** [comment]
A recent hot patch to fix a SPAM issue now requires accounts to leave at least 0.257 tez in there account for now. I recommend leaving a little more - try again with a reduced amount and it should be fine. This will be resolved after the protocol upgrade tomorrow.
