### ISSUE TITLE
cannot add delegate

### ISSUE THREAD

**Issue by jrhite** [tezbox/web-wallet#41]
I'm following the instructions about setting up an account for delegation here: 
https://medium.com/cryptium/how-to-delegate-tezos-xtz-with-tezbox-online-wallet-96592e94e357

My tz1 account is successfully added and I can see my account balance just fine.

I went ahead and created a KT1 account for delegation.

I checked it on https://tzscan.io and the account shows as delegatable. I've tried adding several custom delegators by hand as well as trying using the delegators in the dropdown box. All I see is 'Uh-oh! Delegation failed'.

Tezbox doesn't give me any other info, so I'm not sure how to debug this or what is going wrong.

Can anyone point me in the right direction?

Thanks.

**Comment by jrhite** [comment]
I found this:

a POST to https://rpc.tezrpc.me/chains/main/blocks/head/helpers/preapply/operations was returning a 500 with an error message:

`[{
	"kind": "temporary",
	"id": "proto.003-PsddFKi3.contract.balance_too_low",
	"contract": "KT1Pztcck7q6k5KLoHkSV8hW7u4xv3ofxuFn",
	"balance": "0",
	"amount": "1150"
}]`

(in the article, funding the KT1 account is done after setting a delegate).

From this I figured I just needed to fund my KT1 account. I did so and then adding a delegate worked.

I think better error messaging would make this a non-issue.

**Comment by jrhite** [comment]
I found this:

a POST to https://rpc.tezrpc.me/chains/main/blocks/head/helpers/preapply/operations was returning a 500 with an error message:

`[{
	"kind": "temporary",
	"id": "proto.003-PsddFKi3.contract.balance_too_low",
	"contract": "KT1**********",
	"balance": "0",
	"amount": "1150"
}]`

(in the article, funding the KT1 account is done after setting a delegate).

From this I figured I just needed to fund my KT1 account. I did so and then adding a delegate worked.

I think better error messaging would make this a non-issue.

**Comment by awasunyin** [comment]
Hi, some member from our community had a similar issue. I wanted to confirm if you had the issue when you chose the option "custom" and then added the TZ1 address of the baker in the text field?

If that's the case, the issue must be in how TezBox deals with the custom address text field. I tried with choosing a baker from the drop-down-list and there are no issues with that :/

**Comment by jrhite** [comment]
I had the issue both using custom, and using a baker from the drop-down list. When I funded the KT1 address, it all just worked.

**Comment by stephenandrews** [comment]
The issue is related to users not have the available funds in the KT1 address to cover fees, which are now mandatory after the latest proto updates. The fee amount is cleared displayed, but we will add notifications to ensure the user has enough available balance to cover the fees + fix the error message displayed.
