### ISSUE TITLE
CORS errors from https://mainnet.tezrpc.me

### ISSUE THREAD

**Issue by jekrb** [tezbox/web-wallet#56]
Looks like send errors are being generated because of a CORS error.

Getting `Access to XMLHttpRequest at 'https://mainnet.tezrpc.me/chains/main/blocks/head/helpers/preapply/operations' from origin 'https://wallet.tezbox.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` when trying to send.

![image](https://user-images.githubusercontent.com/2081699/70934116-312d4180-200b-11ea-9ca9-d479e73993c4.png)

**Comment by shaun-19826** [comment]
@jekrb Hello, Has your issue been resolved or you're still having this issue ?

**Comment by jakeburden** [comment]
I believe I was able to get around this issue. It's been a while, so I don't remember exactly what the solution was, but it hasn't been a problem so I'll close this issue.
