### ISSUE TITLE
Randomly can't send tezzies

### ISSUE THREAD

**Issue by Deozaan** [tezbox/web-wallet#9]
Tezbox will randomly not allow me to send from one account to another. An example:

I sent a tiny amount to test. Something like 0.1078. I sent that tiny amount back to make sure I had full control of the wallet.

Then I tried to send my full balance, say 100.1078. It wouldn't send. I can't remember what the error was, but it wasn't helpful. So then I tried to send 99.1078 and it worked, leaving me with a single tez in the wallet. Tezbox refuses to let me send that tez, giving me the same unhelpful error.

I actually had to go through the effort of setting up my own node, exporting my secret key, then importing my secret key to my node, just to send 1 tez to myself.

**Comment by stephenandrews** [comment]
This has been fixed - wallets must leave behind 1mutez (0.000001 tez) in tz accounts. We've added UI improvements to assist with moving the max amount from a wallet.

There was also an issue with dealing with numbers due to an issue with JS - this has been fixed by using the bignumber.js library
